#!/usr/bin/env bash
echo "== put-object"

# Check for bucket name
if [ -z "$1" ]; then
  echo "There needs to be a bucket name eg. ../put-object my-bucket my-file.txt"
  exit 1
fi


# Check for filename
if [ -z "$2" ]; then
  echo "There needs to be a filename eg. ../put-object my-bucket my-file.txt"
  exit 1
fi


aws s3api put-object \
--bucket $BUCKET_NAME
--key $key
--body $FILENAME