---
AWSTemplateFormatVersion: version date

Description:
 "create a template for AWS CloudFormation that defines a set of resources and their configurations"

Metadata:
  template metadata

Parameters:
  set of parameters

Rules:
  set of rules

Mappings:
  set of mappings

Conditions:
  set of conditions

Transform:
  set of transforms

Resources:
  set of resources

Outputs:
  set of outputs
